// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_KEY',
    appId: '1:76527884357:web:d970c007ca935aafc92b2c',
    messagingSenderId: '76527884357',
    projectId: 'flutter-chat-app-8c98b',
    authDomain: 'flutter-chat-app-8c98b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8c98b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_KEY',
    appId: '1:76527884357:android:fc67253f12e9d5edc92b2c',
    messagingSenderId: '76527884357',
    projectId: 'flutter-chat-app-8c98b',
    storageBucket: 'flutter-chat-app-8c98b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_KEY',
    appId: '1:76527884357:ios:4a8ae1213d6274f9c92b2c',
    messagingSenderId: '76527884357',
    projectId: 'flutter-chat-app-8c98b',
    storageBucket: 'flutter-chat-app-8c98b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
